name: 'C++ CI'

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cmake .
      - run: make
      - run: make test
      - run: make package
      - run: ls